CREATE TABLE IF NOT EXISTS users(
    idUser INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nameUser text NOT NULL CHECK (nameUser <> ''),
    passUser integer NOT NULL
);

CREATE TABLE IF NOT EXISTS publications(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    namePublication text NOT NULL CHECK (namePublication <> ''),
    descriptPublication text,
    idUser INTEGER REFERENCES users(idUser)
);





INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a web app', 1, 'using javascript', '2019-05-12');

INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a app mobile', 1, 'using express', '2019-05-13');

INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a table for pg', 1, 'using express', '2019-05-14');

-- INSERT TASKS DATA
INSERT INTO tasks (name, done, projectId)
VALUES ('dowload js', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('create app mobile', true, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('practice java', true, 2);

INSERT INTO tasks (name, done, projectId)
VALUES ('connect database', false, 1);
