CREATE TABLE IF NOT EXISTS clients(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    phone integer NOT NULL,
    email text,
    city text
);

CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nameproduct text NOT NULL CHECK (nameproduct <> ''),
    description text,
    clientid INTEGER REFERENCES clients(id)
);

INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a web app', 1, 'using javascript', '2019-05-12');

INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a app mobile', 1, 'using express', '2019-05-13');

INSERT INTO projects(name,priority, description, deliverydate)
VALUES ('make a table for pg', 1, 'using express', '2019-05-14');

-- INSERT TASKS DATA
INSERT INTO tasks (name, done, projectId)
VALUES ('dowload js', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('create app mobile', true, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('practice java', true, 2);

INSERT INTO tasks (name, done, projectId)
VALUES ('connect database', false, 1);